__STONECRAFT_#FORGE__
__STONECRAFT_#GAMETESTS__
modLoader = "lowcodefml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "${gametestModuleName}"
version = "${version}"
displayName = "${name} Game Tests"
description = '''
GameTests for ${name}
'''

[[dependencies.${gametestModuleName}]]
modId = "${id}"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
__STONECRAFT_/GAMETESTS__
__STONECRAFT_/FORGE__
