org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.caching.debug=false
#org.gradle.configureondemand=true

mod.id=__STONECRAFT_MOD_ID__
mod.name=__STONECRAFT_MOD_NAME__
mod.version=0.0-SNAPSHOT
mod.group=__STONECRAFT_MOD_GROUP__
mod.description=__STONECRAFT_MOD_DESCRIPTION__
